name: Setup
description: Setups node to latest LTS and installs dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
    - run: npm ci
      shell: bash
