---
version: 1
git_protocol: https
editor: code --wait
prompt: enabled
prefer_editor_prompt: disabled
pager: cat
aliases:
  co: pr checkout
  prs: search prs --state open --owner @me
  repo clone_all: |
    !gh repo list --limit 100 --source --no-archived --json name,owner --jq '.[] | .owner.login + " " + .name' | \
    while read -r owner repo; do
      dir="$HOME/repos/$repo"
      if [ ! -d "$dir" ]; then
         echo "🟡 Cloning $owner/$repo"
        gh repo clone "$owner/$repo" "$dir"
      fi
    done
    echo "📦 All repos cloned"
  repo private: repo list --source --visibility private --no-archived
  repo public: repo list --source --visibility public --no-archived
  repo status: |
    !gh repo list --limit 100 --source --no-archived --json nameWithOwner,defaultBranchRef \
      --template '{{range .}}{{.nameWithOwner}} {{.defaultBranchRef.name}}{{"\n"}}{{end}}' | \
    while read -r repo branch; do
      padded=$(printf '%-60s' "$repo")
      gh run list --repo "$repo" --branch "$branch" --limit 1 --json conclusion \
        --template '{{range .}}'"$padded"'{{""}}
          {{- if eq .conclusion "success" -}}
            {{color "green" .conclusion}}
          {{- else if eq .conclusion "failure" -}}
            {{color "red" .conclusion}}
          {{- else -}}
            {{color "yellow" .conclusion}}
          {{- end}}{{"\n"}}
        {{- end}}'
    done
  security: |-
    api repos/{owner}/{repo}/dependabot/alerts
    -q '
      .[] |
      select(.state=="open") |
      "\(.dependency.package.ecosystem)\t" +
      "\(.dependency.package.name)\t" +
      "\u001b[" +
      "\({"critical":"31", "high":"31", "moderate":"33", "low":"32" }[.security_advisory.severity|ascii_downcase])" +
      "m" +
      "\(.security_advisory.severity)\u001b[0m\t" +
      "\u001b[34m\(.html_url)\u001b[0m\t" +
      "\(.security_advisory.summary)"
    '
http_unix_socket:
browser:
